window.LB_SUBJECTS = {
  "Mathematics": {
    key:"math", icon:"math.jpg", accent:"#6c5ce7", tint:"#f3efff",
    desc:"Numbers, fractions, decimals, geometry, measurement, data and problem solving.",
    standardsNote:"Indiana Grade 5 Mathematics (2023 IAS) + the supplied current ILEARN-style focus.",
    units:[
      {id:"math-place",title:"Place Value & Powers of 10",standards:"5.NS.3 · 5.CA.9",strands:["Place value & whole numbers","Decimal operations","Powers of 10"],summary:"Read large numbers and decimals accurately, spot powers-of-ten patterns, and explain what each digit is worth.",teach:["A digit’s value depends on its position. Moving one place left makes its value 10 times greater; moving right makes it one tenth as great.","When multiplying or dividing decimals by powers of 10, describe how place value changes rather than memorizing a ‘move the decimal’ trick.","Estimate first. A reasonable estimate helps catch place-value errors."],example:"3.47 × 100 = 347 because every digit is worth 100 times as much.",challenge:"Explain why 0.62 ÷ 10 is 0.062, not 0.62."},
      {id:"math-compare",title:"Compare Fractions, Mixed Numbers & Decimals",standards:"5.NS.1",strands:["Compare fractions and decimals","Identify greatest value","Order mixed number forms","Compare mixed numbers to thousandths","Number-line midpoint","Place value to thousandths"],summary:"Put different number forms on the same mental number line and compare them precisely.",teach:["Convert numbers to a common form when that makes comparison easier.","Write decimals to the same number of places: 0.5 = 0.500.","On a number line, farther right means greater."],example:"3/4 = 0.75, so 0.72 < 3/4.",challenge:"Order 0.48, 1/2, 0.505 and 49/100 from least to greatest."},
      {id:"math-percent",title:"Percents as Parts of 100",standards:"5.NS.4",strands:["Percents as parts of 100"],summary:"Model a percent as a part of 100 and connect it to an equivalent fraction.",teach:["Percent means “per hundred.” 35% means 35 out of 100.","Write a percent as a fraction over 100 first, then simplify when possible.","Visual 10×10 grids are useful because each small square represents 1%."],example:"25% = 25/100 = 1/4.",challenge:"Shade 60% of a 100-square grid, then write it as a simplified fraction."},
      {id:"math-fractions",title:"Fraction Operations",standards:"5.CA.3–5.CA.8",strands:["Fraction interpretations","Add & subtract fractions","Fraction word problems","Multiply fractions","Fraction multiplication in context","Divide by unit fractions","Fraction division"],summary:"Use models and number sense to add, subtract, multiply and divide fractions.",teach:["For addition and subtraction, create equivalent fractions with a common denominator.","Multiplying by a fraction means taking a part of a quantity.","When dividing, ask how many groups of the divisor fit into the amount."],example:"2/3 + 1/4 = 8/12 + 3/12 = 11/12.",challenge:"Draw or imagine a model for 3/4 × 2/3 before calculating."},
      {id:"math-division",title:"Division & Remainders",standards:"5.CA.1 · 5.CA.2",strands:["Exact division with two-digit divisors","Division with remainders","Check division with multiplication","Reasonableness by multiplication","Partial quotients","Identify quotient and remainder","Multiply in context","Interpret remainder by rounding up","Interpret remainder as leftovers","Budget division and remainder meaning","Multi-step multiplication","Choose division in context"],summary:"Divide larger whole numbers and decide what a remainder means in a real situation.",teach:["Use place value, partial quotients or the standard algorithm—then check with multiplication.","A remainder is not automatically the final answer. Context decides whether to round up, keep leftovers, or report a remainder.","Estimate the quotient first so you know the size of answer to expect."],example:"157 students ÷ 40 per bus = 3 R37, so 4 buses are needed.",challenge:"Explain why 725 ÷ 24 = 30 R5 means 30 full trays and 5 cookies left."},
      {id:"math-decimals",title:"Decimal Operations & Money",standards:"5.CA.9 · 5.CA.10",strands:["Decimal operations"],summary:"Calculate with decimals to hundredths and solve money-based real-world problems.",teach:["Line up place values for addition and subtraction.","Use area or place-value models to understand decimal multiplication and division.","Money problems are decimal problems with units—always label the answer."],example:"$12.50 + $3.75 = $16.25.",challenge:"Estimate first, then solve 7.2 × 0.4."},
      {id:"math-measure",title:"Measurement & Conversions",standards:"5.M.1",strands:["Measurement conversions"],summary:"Convert units within one measurement system and use conversions inside multi-step problems.",teach:["Write the relationship between units before calculating.","Moving to a smaller unit usually makes the number larger; moving to a larger unit makes the number smaller.","Keep units visible throughout a multi-step problem."],example:"3 feet = 36 inches because 1 foot = 12 inches.",challenge:"A ribbon is 5 feet 8 inches long. How many inches is that altogether?"},
      {id:"math-area",title:"Area, Perimeter & Shapes",standards:"5.M.2 · 5.M.3",strands:["Fractional area","Area of triangles & quadrilaterals"],summary:"Reason about area and perimeter, including fractional side lengths, triangles, parallelograms and trapezoids.",teach:["Area measures surface in square units; perimeter measures distance around a boundary.","A parallelogram’s area is base × height; a triangle with the same base and height has half that area.","For fractional side lengths, multiplication still represents rows × columns of fractional-size units."],example:"A triangle with base 8 cm and height 5 cm has area 20 cm².",challenge:"Why is slanted side length not automatically the height of a parallelogram?"},
      {id:"math-volume",title:"Volume Lab",standards:"5.M.4 · 5.M.5",strands:["Unit cubes from dimensions","Layers and base area","Find the number of layers","Match dimensions to volume","Missing dimension with cubes","Explain volume reasoning","Use V = l × w × h","Use V = B × h","Find a missing height","Find base area from volume","Compare volumes","Choose a volume equation"],summary:"Build volume from unit cubes, layers and the formulas V = l × w × h and V = B × h.",teach:["Volume counts the number of cubic units that fill a 3D space.","Find cubes in one layer (base area), then multiply by the number of layers.","If a dimension is missing, divide the total volume by the product of the known dimensions."],example:"A 4 × 3 × 2 prism has 12 cubes per layer and 2 layers: 24 cubic units.",challenge:"A prism has volume 360 in³, length 12 in and width 5 in. Find its height."},
      {id:"math-geometry",title:"Geometry, Circles & Coordinates",standards:"5.G.1 · 5.CA.11",strands:["Geometry & classification","Circles: radius & diameter","Coordinate plane"],summary:"Classify shapes, connect radius and diameter, and represent situations with ordered pairs.",teach:["Triangles can be classified by angle type: acute, right or obtuse.","The diameter passes through the center and is twice the radius.","In an ordered pair (x, y), move horizontally by x and vertically by y."],example:"If radius = 6 cm, diameter = 12 cm.",challenge:"Plot (4, 3) and explain what each coordinate could mean in a real situation."},
      {id:"math-data",title:"Data & Typical Values",standards:"5.DA.1 · 5.DA.2",strands:["Data displays","Mean, median & mode"],summary:"Collect, display and interpret data, then choose mean, median or mode appropriately.",teach:["A graph should match the type of data and the question you want to answer.","Mean shares the total equally; median is the middle value; mode is most frequent.","Outliers can change the mean more than the median."],example:"For 2, 3, 3, 4, 8: mean = 4, median = 3, mode = 3.",challenge:"Which measure best represents a set with one extremely large outlier? Explain."},
      {id:"math-order",title:"Expressions & Order of Operations",standards:"Grade 5 process skill",strands:["Order of operations"],summary:"Evaluate multi-step numerical expressions in a consistent order and explain each step.",teach:["Work inside grouping symbols first.","Multiply and divide before adding and subtracting, moving left to right within each level.","Write one line per step so your reasoning is easy to check."],example:"18 − 3 × 4 = 18 − 12 = 6.",challenge:"Explain why 6 + 2 × 5 is not 40."}
    ]
  },
  "English Language Arts": {
    key:"ela", icon:"ela.jpg", accent:"#ff6b6b", tint:"#fff0f0",
    desc:"Reading, vocabulary, grammar, writing, speaking and evidence-based thinking.",
    standardsNote:"Indiana Grade 5 ELA (2023 IAS): Reading Foundations, Reading Comprehension, Writing, Communication & Collaboration.",
    units:[
      {id:"ela-word",title:"Word Detective",standards:"5.RF.1 · vocabulary",strands:["Vocabulary & morphology","Vocabulary in context"],summary:"Use roots, prefixes, suffixes and context to unlock unfamiliar words.",teach:["Break a long word into meaningful parts before guessing.","A prefix changes the beginning of meaning; a suffix often changes meaning or grammatical role.","Use the whole sentence to check whether your word meaning makes sense."],example:"reusable = re- (again) + use + -able (can be): able to be used again.",challenge:"What does ‘unpredictable’ suggest from its word parts?"},
      {id:"ela-lit",title:"Stories: Theme, Character & Inference",standards:"5.RC.1–5.RC.3",strands:["Reading comprehension: literature","Text evidence"],summary:"Read closely, infer carefully and support ideas with evidence from the text.",teach:["An inference combines text evidence with what you already know.","Theme is a broader message developed through events and character choices—not a one-word topic.","Strong answers point to specific details instead of saying only ‘because the story says so.’"],example:"If a character keeps trying after several failures, evidence may support a theme about perseverance.",challenge:"State a theme in a full sentence and name two details that develop it."},
      {id:"ela-info",title:"Informational Reading",standards:"5.RC informational text",strands:["Reading comprehension: informational","Text evidence","Text structure"],summary:"Find main ideas, supporting details, relationships and text structures in nonfiction.",teach:["Ask what the whole section is mostly teaching, then identify details that directly support it.","Common structures include cause/effect, compare/contrast, sequence and problem/solution.","Headings, captions and diagrams are part of the text and can carry evidence."],example:"A passage explaining why floods happen uses cause-and-effect relationships.",challenge:"How does recognizing text structure help you summarize?"},
      {id:"ela-craft",title:"Author Craft & Point of View",standards:"5.RC craft and structure",strands:["Author craft & structure","Text structure"],summary:"Notice how authors organize ideas and choose words to shape meaning and tone.",teach:["Ask why the author chose this detail, order or phrase.","Point of view changes what the reader knows and how events are presented.","Figurative language creates an effect; identify the effect, not only the device."],example:"Calling a busy hallway ‘a river of backpacks’ emphasizes continuous movement.",challenge:"Rewrite one sentence from another character’s point of view."},
      {id:"ela-grammar",title:"Grammar & Punctuation Workshop",standards:"Grade 5 language conventions",strands:["Grammar & usage","Punctuation & conventions"],summary:"Build clear sentences with accurate grammar, punctuation and usage.",teach:["A complete sentence needs a subject and a predicate and must express a complete thought.","Use commas and punctuation to show structure and prevent misreading.","Read the sentence aloud after editing; your ear often catches missing words or awkward phrasing."],example:"After lunch, Maya finished the model, checked the labels, and packed it carefully.",challenge:"Edit a sentence with one run-on, one punctuation error and one unclear pronoun."},
      {id:"ela-writing",title:"Writing Studio",standards:"5.W.1–5.W.4",strands:["Writing organization","Grammar & usage","Punctuation & conventions"],summary:"Plan, draft, revise and edit persuasive, informative and narrative writing.",teach:["Start with purpose and audience: what should the reader know, think or feel?","Group related ideas and use transitions to make the structure visible.","Revision improves ideas and organization; editing fixes conventions. They are different jobs."],example:"A persuasive paragraph states a position, supports it with reasons/evidence, and connects each reason back to the position.",challenge:"Write a 3-sentence mini-argument with a claim, evidence and explanation."},
      {id:"ela-talk",title:"Speaking, Listening & Media",standards:"5.CC",strands:["Reading comprehension: informational"],summary:"Explain ideas clearly, build on another person’s thinking and evaluate information from media.",teach:["Listen for the speaker’s main claim and evidence before responding.","Build on ideas with sentence starters such as ‘I agree because…’ or ‘Another piece of evidence is…’.","Ask who created a media message, what evidence is provided and what might be missing."],example:"A strong response refers to the previous speaker’s idea before adding a new point.",challenge:"Summarize a claim in one sentence, then ask one useful follow-up question."}
    ]
  },
  "Science": {
    key:"science", icon:"science.jpg", accent:"#00a878", tint:"#e7fff7",
    desc:"Matter, forces, ecosystems, Earth and space, and engineering investigations.",
    standardsNote:"Indiana Grade 5 Science (2023 IAS / NGSS-aligned performance expectations).",
    units:[
      {id:"sci-matter",title:"Matter: Invisible Particles",standards:"5-PS1-1",strands:["Matter & particles"],summary:"Use models to explain that matter is made of particles too small to see directly.",teach:["A model is a useful representation, not an exact miniature of reality.","Dissolving does not make matter vanish; particles can spread through a liquid.","Gases are matter too: they take up space and can be compressed."],example:"Inflating a ball shows that added air particles take up space.",challenge:"How could dissolving sugar in water support a particle model?"},
      {id:"sci-change",title:"Changes, Properties & New Substances",standards:"5-PS1-2 · 5-PS1-3 · 5-PS1-4",strands:["Matter & particles"],summary:"Measure properties, track mass through changes and distinguish mixtures from evidence of new substances.",teach:["Physical properties such as hardness, reflectivity, conductivity and solubility help identify materials.","In a closed system, matter is conserved during heating, cooling, dissolving and mixing.","Unexpected gas, temperature change, color change or a new solid can be evidence that new substances formed—but evidence must be interpreted carefully."],example:"If ice melts in a sealed container, total mass stays the same.",challenge:"Design a fair observation to compare the solubility of two powders."},
      {id:"sci-gravity",title:"Gravity",standards:"5-PS2-1",strands:["Forces & energy"],summary:"Build an evidence-based argument that Earth’s gravitational force points toward Earth’s center.",teach:["‘Down’ means toward Earth’s center from your local position.","A scientific argument includes a claim, evidence and reasoning.","Objects on opposite sides of Earth both experience gravity toward the planet’s center."],example:"A dropped ball accelerates toward the ground because Earth pulls it toward its center.",challenge:"Why don’t people in the Southern Hemisphere fall off Earth?"},
      {id:"sci-energy",title:"Sun → Plants → Animals",standards:"5-PS3-1",strands:["Forces & energy","Life science"],summary:"Trace the energy in food back to sunlight captured by plants.",teach:["Plants capture light energy and store it in matter they make.","Animals obtain that stored energy by eating plants or other animals.","Energy flow and matter movement are related but not identical ideas."],example:"Sunlight → grass → rabbit → fox is an energy pathway.",challenge:"Trace the energy in a cheese sandwich back toward its original source."},
      {id:"sci-plants",title:"Plant Growth & Ecosystems",standards:"5-LS1-1 · 5-LS2-1",strands:["Life science"],summary:"Explain where plant matter comes from and model how matter cycles through ecosystems.",teach:["Plants get most material for growth from air and water, not by ‘eating’ soil.","Matter moves among producers, consumers, decomposers and the environment.","Decomposers return materials to the environment where they can be reused."],example:"Carbon dioxide from air and water contribute to new plant matter.",challenge:"Draw a matter cycle with a plant, animal, decomposer, air, water and soil."},
      {id:"sci-space",title:"Stars, Shadows & Sky Patterns",standards:"5-ESS1-1 · 5-ESS1-2",strands:["Earth & space"],summary:"Use patterns and data to reason about apparent brightness, shadows, day/night and seasonal stars.",teach:["A star’s apparent brightness depends partly on distance from Earth.","Shadow length and direction change predictably as the Sun appears to move across the sky.","Graphs help reveal repeated daily or seasonal patterns."],example:"Near midday, a vertical object’s shadow is often shorter than early morning or late afternoon.",challenge:"What data would you collect for a week to study shadow patterns?"},
      {id:"sci-earth",title:"Earth Systems & Water",standards:"5-ESS2-1 · 5-ESS2-2",strands:["Earth & space"],summary:"Model interactions among the geosphere, hydrosphere, atmosphere and biosphere and analyze Earth’s water distribution.",teach:["Earth systems continuously interact; a change in one can affect others.","Most of Earth’s water is salty ocean water. Much fresh water is frozen or underground.","Models and graphs can make quantities and system interactions easier to reason about."],example:"Rain (atmosphere/hydrosphere) erodes soil (geosphere) and affects plants (biosphere).",challenge:"Explain two ways a drought can affect more than one Earth system."},
      {id:"sci-impact",title:"Protecting Earth’s Resources",standards:"5-ESS3-1",strands:["Earth & space"],summary:"Combine information to evaluate actions communities use to protect resources and environments.",teach:["Environmental decisions involve evidence, benefits, limits and trade-offs.","Conservation can reduce waste, protect habitats or preserve water and soil.","A good solution is specific enough to test or measure."],example:"A town can reduce polluted runoff with planted buffer zones near streams.",challenge:"Choose one local resource and propose a measurable protection action."},
      {id:"sci-engineer",title:"Engineering Design",standards:"3-5-ETS1-1 · 3-5-ETS1-2 · 3-5-ETS1-3",strands:["Engineering design"],summary:"Define problems, compare solutions and improve designs using fair tests.",teach:["Criteria describe what success must look like; constraints set limits such as time, cost or materials.","Compare more than one possible solution before choosing.","A fair test changes one important variable at a time and uses results to improve the design."],example:"For a paper bridge, criteria might include holding 20 coins; constraints might include one sheet of paper and 10 minutes.",challenge:"Name one variable you would control in a paper-airplane test."}
    ]
  },
  "Social Studies": {
    key:"social", icon:"social.jpg", accent:"#f59e0b", tint:"#fff7e6",
    desc:"Early America, the Revolution, civics, U.S. geography and economic decision making.",
    standardsNote:"Indiana Grade 5 Social Studies domains: History, Civics & Government, Geography and Economics.",
    units:[
      {id:"ss-indigenous",title:"North America Before European Colonization",standards:"History",strands:["History","Geography"],summary:"Study diverse Indigenous cultures and how communities adapted to different environments.",teach:["North America contained many distinct societies with different languages, governments, technologies and traditions.","Environment influenced food, housing, movement and trade, but did not determine culture by itself.","Use specific evidence rather than treating Indigenous peoples as one single group."],example:"Different regions supported different food systems, building materials and travel methods.",challenge:"Compare two regions using environment, food and housing as evidence."},
      {id:"ss-explore",title:"Exploration, Contact & Colonization",standards:"History · Geography · Economics",strands:["History","Geography","Economics"],summary:"Examine motives, routes, settlements, trade and the consequences of contact.",teach:["European exploration involved economic, political and religious motives.","Contact created exchange, cooperation and conflict—and caused severe disruption and disease for Indigenous communities.","Maps help reveal how waterways, coastlines and resources shaped settlements."],example:"Ports and rivers mattered because they supported transport and trade.",challenge:"Separate one motive for exploration from one consequence of colonization."},
      {id:"ss-colonies",title:"The Thirteen Colonies",standards:"History · Geography · Economics",strands:["History","Geography","Economics"],summary:"Locate the colonies by region and compare government, society and economic activity.",teach:["New England, Middle and Southern colonies developed different patterns of settlement and work.","Climate, soil, waterways and access to ports influenced economic choices.","Colonial society included deep inequalities, including slavery and limits on political participation."],example:"Regional economies differed because resources, climate and labor systems differed.",challenge:"Explain one way geography influenced a colonial region’s economy."},
      {id:"ss-revolution",title:"Road to Revolution",standards:"History",strands:["History"],summary:"Connect British policies, colonial responses, the Declaration of Independence and key events of the Revolutionary War.",teach:["Historical causes build over time; avoid explaining a revolution with one event only.","The Declaration of Independence states grievances and political principles used to justify separation.","Different people and nations contributed to the war in different ways."],example:"A chain of cause/effect might connect taxes, protest, British response and growing demands for independence.",challenge:"Build a four-step cause-and-effect chain leading toward independence."},
      {id:"ss-founding",title:"Constitution & Bill of Rights",standards:"History · Civics",strands:["History","Civics & Government"],summary:"Understand why the Constitution replaced the Articles of Confederation and how the Bill of Rights protects liberties.",teach:["The Constitution created a stronger national framework while dividing and limiting government power.","The Bill of Rights lists protections against government overreach and protects specific liberties.","Primary sources should be read in historical context as well as connected to civic principles."],example:"Separation of powers gives different responsibilities to legislative, executive and judicial branches.",challenge:"Explain how a limit on government power can protect individual liberty."},
      {id:"ss-civics",title:"Government, Elections & Civic Participation",standards:"Civics & Government",strands:["Civics & Government"],summary:"Learn the branches of government, elections, civic virtues and ways citizens participate.",teach:["Legislative bodies make laws, executives carry them out, and courts interpret laws.","Checks and balances distribute authority so no branch acts without limits.","Civic participation includes more than voting: people can learn, communicate, organize and serve."],example:"A court can review whether government action is consistent with law and constitutional rules.",challenge:"Give one example of responsible civic participation that does not involve an election."},
      {id:"ss-geography",title:"Maps, Regions & U.S. Geography",standards:"Geography",strands:["Geography"],summary:"Use latitude/longitude and maps to locate places, regions, physical features and water resources.",teach:["Latitude measures north/south position; longitude measures east/west position.","Physical features influence transportation, settlement, climate and economic activity.","Maps are selective models—always check title, scale, legend and purpose."],example:"A river may support transportation, freshwater access and settlement while also creating flood risk.",challenge:"Why might two maps of the same place emphasize different information?"},
      {id:"ss-econ",title:"Economics & Personal Decisions",standards:"Economics",strands:["Economics"],summary:"Reason about trade, productivity, supply and demand, and household budgeting.",teach:["People make choices because time, money and resources are limited.","Technology, education and specialization can increase productivity.","Prices can respond to changes in supply and demand, but real markets can involve other influences too."],example:"If demand rises while supply stays the same, upward pressure on price can result.",challenge:"Create a simple budget with income, needs, savings and one optional expense."}
    ]
  },
  "Computer Science & STEM": {
    key:"cs", icon:"cs.jpg", accent:"#2563eb", tint:"#eaf2ff",
    desc:"Algorithms, debugging, data, digital citizenship and engineering design.",
    standardsNote:"Indiana Grades 3–5 Computer Science + integrated STEM practices.",
    units:[
      {id:"cs-algo",title:"Algorithms & Clear Instructions",standards:"Grades 3–5 CS",strands:["Algorithms"],summary:"Turn a goal into ordered, precise steps that someone—or a computer—can follow.",teach:["An algorithm is a sequence of instructions designed to complete a task.","Precision matters because computers do not automatically infer missing steps.","Breaking a large task into smaller steps is called decomposition."],example:"A recipe is an everyday algorithm: ingredients, ordered steps and conditions.",challenge:"Write an algorithm for making a paper airplane using no vague words like ‘properly’."},
      {id:"cs-debug",title:"Debugging",standards:"Grades 3–5 CS",strands:["Debugging"],summary:"Find where a process goes wrong, test a fix and verify the result.",teach:["A bug is an error in a program or process.","Debug systematically: reproduce the problem, isolate a likely cause, change one thing, test again.","A fix is not finished until you test that it solved the problem without breaking something else."],example:"If a character moves left instead of right, inspect the direction instruction before rewriting the whole program.",challenge:"Describe a debugging plan for instructions that sometimes skip a step."},
      {id:"cs-data",title:"Data & Patterns",standards:"Grades 3–5 CS",strands:["Data & patterns"],summary:"Organize information so patterns, comparisons and errors are easier to spot.",teach:["Data become useful when they are organized and interpreted.","Tables are good for exact values; graphs are often better for patterns.","Check how data were collected before trusting a conclusion."],example:"A weekly temperature chart can reveal a trend that is hard to see from an unordered list.",challenge:"Choose a chart type for comparing five categories and explain why."},
      {id:"cs-digital",title:"Digital Citizenship",standards:"Grades 3–5 CS",strands:["Digital citizenship"],summary:"Protect privacy, evaluate online information and communicate responsibly.",teach:["Personal information should be shared carefully and only with trusted permission.","Online content can be incomplete, misleading or designed to persuade; check source and evidence.","Kind, clear communication and reporting unsafe behavior are part of responsible digital participation."],example:"Before trusting a claim, check who published it, when, and whether other reliable sources agree.",challenge:"List three clues that would make you question an online claim."},
      {id:"cs-engineer",title:"Design, Build, Test, Improve",standards:"Integrated STEM · 3-5-ETS",strands:["Engineering"],summary:"Use criteria, constraints and evidence to improve a solution through iterations.",teach:["Define what the design must do before building.","A prototype is for learning—not just showing a finished idea.","Use test results to decide what to change next."],example:"A tower challenge might require 30 cm height using only paper and tape.",challenge:"Name one criterion, one constraint and one measurable test for a shelter design."}
    ]
  },
  "Health & Wellbeing": {
    key:"health", icon:"health.jpg", accent:"#ec4899", tint:"#fff0f7",
    desc:"Healthy routines, safety, emotions, relationships and sensible everyday choices.",
    standardsNote:"Home-learning enrichment informed by Grade 5 health and wellness themes.",
    units:[
      {id:"health-body",title:"Everyday Healthy Habits",standards:"Grade 5 Health & Wellness",strands:["Healthy habits"],summary:"Build routines around sleep, hydration, food, hygiene and movement.",teach:["Healthy routines work best when they are realistic and repeatable.","Balanced choices across food, water, sleep and activity support learning and wellbeing.","One choice does not define health; patterns over time matter more."],example:"Packing water, a varied lunch and planning active time are examples of practical habits.",challenge:"Choose one routine to make easier by changing the environment around you."},
      {id:"health-mind",title:"Feelings, Stress & Focus",standards:"Grade 5 Health & Wellness",strands:["Emotional wellbeing"],summary:"Recognize emotions, use healthy coping strategies and ask for support when needed.",teach:["Naming a feeling can make it easier to choose what to do next.","Helpful strategies can include a short break, slow breathing, movement, writing or talking to a trusted adult.","Strong or persistent worries deserve support from a trusted adult rather than being handled alone."],example:"Before a difficult task, a student might take three slow breaths and break the task into smaller steps.",challenge:"Make a two-step plan for what to do when frustration starts to interfere with learning."},
      {id:"health-safe",title:"Safety & Digital Wellbeing",standards:"Grade 5 Health & Wellness",strands:["Safety & digital wellbeing"],summary:"Make safer choices at home, outdoors and online.",teach:["Pause before sharing personal information, images or location online.","If something online feels threatening, sexual, secretive or unsafe, stop and tell a trusted adult.","In a serious emergency, get a responsible adult and emergency help rather than trying to manage it alone."],example:"A message asking for a home address should not be answered without a trusted adult’s involvement.",challenge:"Create a three-question safety check to use before posting or replying online."},
      {id:"health-people",title:"Communication & Respect",standards:"Grade 5 Health & Wellness",strands:["Communication & respect"],summary:"Practice clear boundaries, respectful disagreement and help-seeking.",teach:["You can disagree without insulting another person.","A boundary states what you are or are not comfortable with and what you need to happen next.","Trusted adults can help when a situation feels unsafe, confusing or too difficult to solve alone."],example:"‘I don’t want to share that. Please stop asking.’ is a clear boundary.",challenge:"Rewrite a rude disagreement as a calm, specific response."}
    ]
  },
  "Creative Arts": {
    key:"arts", icon:"arts.jpg", accent:"#8b5cf6", tint:"#f4eeff",
    desc:"Visual art, music, design and creative communication through hands-on mini projects.",
    standardsNote:"Grade 5 creative enrichment informed by visual arts and music learning practices.",
    units:[
      {id:"art-elements",title:"Elements of Visual Art",standards:"Grade 5 Fine Arts",strands:["Visual art"],summary:"Use line, shape, form, color, value, texture and space deliberately.",teach:["Artists combine visual elements to guide attention and create mood.","Value means lightness or darkness; texture can be real or implied.","Foreground, middle ground and background can create a sense of space."],example:"Overlapping shapes and making distant objects smaller can suggest depth.",challenge:"Create a tiny sketch using at least four different kinds of line."},
      {id:"art-design",title:"Design & Composition",standards:"Grade 5 Fine Arts",strands:["Visual art"],summary:"Arrange visual elements so the viewer knows what matters most.",teach:["Contrast creates difference; balance distributes visual weight; repetition can create rhythm.","A focal point is where attention goes first.","Good design comes from making intentional choices, then revising."],example:"A bright shape against a quiet background creates strong contrast and a focal point.",challenge:"Redesign a simple poster so the most important information is seen first."},
      {id:"art-music",title:"Music: Rhythm, Tempo & Dynamics",standards:"Grade 5 Fine Arts",strands:["Music"],summary:"Listen for and create patterns using beat, rhythm, tempo and dynamics.",teach:["Beat is the steady pulse; rhythm is the pattern of long and short sounds around the beat.","Tempo describes speed; dynamics describe loudness and softness.","Repeated musical ideas can create structure and expectation."],example:"A piece can keep the same rhythm while changing tempo or dynamics.",challenge:"Clap a four-beat pattern, repeat it, then change only the dynamics."},
      {id:"art-story",title:"Creative Storytelling",standards:"Grade 5 Fine Arts",strands:["Creative storytelling"],summary:"Use image, sound, movement or words to communicate a clear idea or mood.",teach:["Creative choices should support the intended message.","A beginning establishes context, a middle develops tension or change, and an ending resolves or reframes the idea.","Reflection asks what worked, what the audience understood and what you would change."],example:"A short scene can show nervousness through pacing, repeated sound and limited color before any dialogue is spoken.",challenge:"Plan a 30-second story with one image, one sound and one line of dialogue."}
    ]
  }
};

window.LB_RESOURCES = [
  {subject:"Mathematics",title:"Indiana Academic Standards — Mathematics",url:"https://www.in.gov/doe/students/indiana-academic-standards/mathematics/",note:"Used to structure Grade 5 math domains and skills."},
  {subject:"English Language Arts",title:"Indiana Academic Standards — English/Language Arts",url:"https://www.in.gov/doe/students/indiana-academic-standards/englishlanguage-arts/",note:"Used to structure reading foundations, comprehension, writing and communication."},
  {subject:"Science",title:"Indiana Academic Standards — Science & Computer Science",url:"https://www.in.gov/doe/students/indiana-academic-standards/science-and-computer-science/",note:"Used to structure Grade 5 science and Grade 3–5 computer science."},
  {subject:"Social Studies",title:"Indiana Academic Standards — Social Studies",url:"https://www.in.gov/doe/students/indiana-academic-standards/social-studies/",note:"Used for Grade 5 history, civics, geography and economics structure."},
  {subject:"Assessment",title:"Indiana ILEARN Assessment Frameworks",url:"https://www.in.gov/doe/students/assessment/ilearn/",note:"Used to keep checks focused on reasoning, evidence and grade-level expectations."},
  {subject:"Science",title:"NASA STEM — Exploring the Water Cycle",url:"https://www.nasa.gov/stem-content/exploring-the-water-cycle/",note:"Informed Earth-systems lesson design and hands-on questioning."},
  {subject:"Science",title:"NASA STEM — Earth's Water",url:"https://www.nasa.gov/stem-content/earths-water/",note:"Informed Grade 5 water-distribution learning activities."},
  {subject:"Social Studies",title:"National Archives — Constitution Workshop",url:"https://www.archives.gov/education/lessons/constitution-workshop",note:"Informed primary-source and evidence-based civics activities."}
];

window.LB_SCHOOL_FOCUS = {
  title:"Current school math focus",
  subtitle:"From the supplied Grade 5 ILEARN-style practice",
  standards:["5.M.4","5.M.5","5.NS.1","5.CA.1","5.CA.2"],
  subject:"Mathematics"
};
